### ISSUE TITLE
AlgorithmError: InstallModuleError:

### ISSUE THREAD

**Issue by nbxszby416** [nwcd-samples/NWCD-Industry-Customized-OCR-Solution#1]
Hi, when I tried to use the sagemaker method to build the demo, I got this error in the training part:

**sagemaker-containers ERROR InstallModuleError:
Command "/opt/conda/bin/python -m pip install . -r requirements.txt"**

I'm not sure whether it is something wrong with the image you have provided, or something else which could accidentally result in this  error.

**Comment by dikers** [comment]
执行哪个文件报错了？  有详细的log信息吗？

**Comment by nbxszby416** [comment]
已经解决了！还是感谢！（虽然不知道是什么原因，但是后来再跑就直接跑通了~）
